line-length = 100
target-version = "py312"
extend-exclude = ["alembic"]

[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "SIM", "RUF"]
ignore = ["E501", "RUF059", "SIM117"]

[lint.isort]
known-first-party = ["nexus"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
